version: "3"

services:
    web:
        container_name: socialubb
        restart: always
        build: .
        ports:
            - "4001:3001"
        links:
            - mongo
        volumes:
            - .:/app
    mongo:
      container_name: mongodatabase
      image: mongo
      ports:
          - "27018:27017"
      logging:
          driver: none
